name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: '^13.2'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
