name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: macos-11
    env:
      SCHEME: AsyncView
    steps:
    - uses: actions/checkout@v2
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: '^13.2'
    - name: List Xcode destinations
      run: xcodebuild -scheme "${{ env.SCHEME }}" -showdestinations
    - name: Build
      run: xcodebuild -scheme "${{ env.SCHEME }}" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
    - name: Run tests
      run: xcodebuild -scheme "${{ env.SCHEME }}" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' test-without-building
